// Create new HTML for character sheet generated by kcg form
// this is a horrible relic of ancient days

function generateCharacterSheet() {
	//since all variable MUST be declared at top, I'll declare the start of the newPage here...
	var newPage = '<!DOCTYPE html><html><head><title>Your New Khajiit</title><meta charset="utf-8" /><link rel="stylesheet" href="css/khajiit2.css" /></head><body>'; 
	//and THEN run through all of the bits before printing out the rest....
	
	//define all attributes and skills at default level one values
	var strength = 35;
	var wisdom = 30;
	var endurance = 35;
	var charisma = 40;
	var intelligence = 40;
	var agility = 50;
	var luck = 40;
	var speed = 30;
	var health = 100;
	var magicka = 50;
	var stamina = 150;
	var alteration = 10;
	var conjuration = 10;
	var destruction = 10;
	var illusion = 10;
	var restoration = 10;
	var enchantment = 10;
	var archery = 10; 
	var block = 10;
	var heavyarmor = 10;
	var onehanded = 10;
	var twohanded = 10;
	var unarmed = 15;
	var acrobatics = 25;
	var disguise = 10;
	var lightarmor = 15;
	var fraud = 10;
	var security = 15;
	var sneak = 20;
	var alchemy = 10;
	var speech = 10;
	var linguistics = 15;
	var handcraft = 20;
	var perform = 10;
	var smith = 10;
	
	var role = "role";
	var morph = "morph";
	
	var rolecheck = document.kcg.elements[role];
   for(var i = 0; i < rolecheck.length; i++)
   {
      if(rolecheck[i].checked)
      {
        var role = rolecheck[i].value;
      }
   }
   
   
	var morphcheck = document.kcg.elements[morph];
   for(var i = 0; i < morphcheck.length; i++)
   {
      if(morphcheck[i].checked)
      {
        var morph = morphcheck[i].value;
      }
   }
	
	//help from http://www.javascript-coder.com/javascript-form/javascript-get-check.phtml
	//and http://www.openjs.com/tutorials/advanced_tutorial/choices.php
	// as there is a dearth of info on using radio buttons with JS
	
	// make changes depending on role chosen
	switch (role) {
		case 'magic':
      wisdom += 10;
      magicka +=50;
      alteration += 10;
      conjuration += 10;
      destruction += 10;
      illusion += 10;
      restoration += 10;
      enchantment += 10;
      alchemy += 10;
		break;
		case 'combat':
      strength +=10;
      health += 50;
      archery += 10;
      block += 10;
      heavyarmor += 10;
      onehanded += 10;
      twohanded += 10;
      unarmed += 10;
      smith += 10;
		break;
		case 'stealth':
      agility += 10;
      stamina += 50;
      acrobatics += 10;
      disguise += 10;
      lightarmor += 10;
      fraud += 10;
      security += 10;
      sneak += 10;
      archery += 10;
		break;
		case 'craft':
      luck += 10;
      intelligence += 10;
      alchemy += 10;
      speech += 10;
      linguistics += 10;
      handcraft += 10;
      perform += 10;
      smith += 10;
      unarmed += 10;
		break;
		default:
		break;
	
	}
	
	// make changes depending on morph chosen
	switch (morph) {
		case 'ohmes':
      charisma +=5;
      strength -= 5;
      disguise +=10;
		break;
		case 'dagi':
      wisdom +=10;
      strength -=10;
      magicka += 10;
      sneak +=10;
		break;
		case 'cathay':
      strength +=5;
      agility -=5;
      stamina += 10;
		break;
		case 'alfiq':
      agility += 10;
      strength -= 10;
      unarmed += 5;
      sneak += 10;
      archery = 0;
      handcraft = 0;
      onehanded = 0;
      smith = 0;
      twohanded = 0;
      security = 0;
		break;
		case 'pahmar':
      strength +=5;
      unarmed += 10;
      speed += 10;
      archery = 0;
      handcraft = 0;
      onehanded = 0;
      smith = 0;
      twohanded = 0;
		break;
		case 'senche':
      strength +=10;
      agility -=10;
      unarmed += 15;
      health += 10;
      archery = 0;
      handcraft = 0;
      onehanded = 0;
      smith = 0;
      twohanded = 0;
		break;
		default:
		break;
	}
	
	// and finally print out results in the rest of the page!
	newPage += "<h2>" + kcg.charname.value + ": a specialist in " + role + "</h2>";
	newPage += "<table><caption>Attributes: Level 1</caption>";
	newPage += "<tr><td>Health</td><td>Magicka</td><td>Stamina</td><td>Speed</td><td>Morph</td><td>Age</<td><td>Gender</td></tr>";
	newPage += "<tr><td>" + health + "</td><td>" + magicka + "</td><td>" + stamina + "</td><td>" + speed + "</td><td>" + morph + "</td><td>" + kcg.charage.value + "</td><td>" + kcg.chargend.value + "</td></tr>";
	newPage += "<tr><td>Strength</td><td>Wisdom</td><td>Endurance</td><td>Charisma</td><td>Intelligence</td><td>Agility</td><td>Luck</td><td></tr>";
	newPage += "<tr><td>" + strength + "</td><td>" + wisdom + "</td><td>" + endurance + "</td><td>" + charisma + "</td><td>" + intelligence + "</td><td>" + agility + "</td><td>" + luck + "</td></tr>";
	newPage += "</table>"; //end attributes table
	//now the skills table
	newPage += "<table><caption>Skills: Level 1</caption>"; 
	newPage += "<tr><td>Alteration</td><td>Conjuration</td><td>Destruction</td><td>Illusion</td><td>Restoration</td><td>Enchantment</td></tr>";
	newPage += "<tr><td>" + alteration + "</td><td>" + conjuration + "</td><td>" + destruction + "</td><td>" + illusion + "</td><td>" + restoration + "</td><td>" + enchantment + "</td></tr>";
	newPage += "<tr><td>Archery</td><td>Block</td><td>Heavy Armor</td><td>One handed</td><td>Two Handed</td><td>Unarmed</td></tr>";
	newPage += "<tr><td>" + archery + "</td><td>" + block + "</td><td>" + heavyarmor + "</td><td>" + onehanded + "</td><td>" + twohanded + "</td><td>" + unarmed + "</td></tr>";
	newPage += "<tr><td>Acrobatics</td><td>Disguise</td><td>Light Armor</td><td>Fraud</td><td>Security</td><td>Sneak</td></tr>";
	newPage += "<tr><td>" + acrobatics + "</td><td>" + disguise + "</td><td>" + lightarmor + "</td><td>" + fraud + "</td><td>" + security + "</td><td>" + sneak + "</td></tr>";
	newPage += "<tr><td>Alchemy</td><td>Speech</td><td>Linguistics</td><td>Handcraft</td><td>Perform</td><td>Smith</td></tr>";
	newPage += "<tr><td>" + alchemy + "</td><td>" + speech + "</td><td>" + linguistics + "</td><td>" + handcraft + "</td><td>" + perform + "</td><td>" + smith + "</td></tr>";
	newPage += "</table>"; //end skills table
	newPage += "<h5>Inventory</h5>";
	switch(role){
		case 'magic':
		newPage += "<p>As a magic specialist, you have a tattered star covered robe (+13 to magicka), socks that are two sizes too big, and a sweet roll.</p>";
		break;
		case 'combat':
		newPage += "<p>As a combat specialist, you have rusty iron chainmail, a big stick with a nail in it, and a ration of jerky.</p>";
		break;
		case 'stealth': 
		newPage += "<p>As a stealth specialist, you have greasy leather armor, a ski mask, and a lockpick.</p>";
		break;
		case 'craft':
		newPage += "<p>As a craft specialist, you have a dirty peasant shirt, yarn, a bag of seeds, and a shovel.</p>";
		break;
		default:
		break;
	}
	newPage += "<h5>Khajiit Special Abilities and Limitations</h5>";
	newPage += "<p>All Khajiit have Night Eye ability, which is automatic in the dark.</p>";
		switch (morph) {
		case 'ohmes':
		newPage += "<p>As an Ohmes, you have Claws (8 pt).</p>";
		break;
		case 'dagi':
		newPage += "<p>As a Dagi, you have Bite (6 points) and Claws (8 pt).</p>";
		break;
		case 'suthay':
		newPage += "<p>As a Suthay, you have Bite (8 pt) and Claws (12 pt).</p>";
		break;
		case 'cathay':
		newPage += "<p>As a Cathay, you have Bite (10 points) and Claws (15 pt). As a large cat, you can use your claws in place of lockpicks.</p>";
		break;
		case 'alfiq':
		newPage += "<p>As an Alfiq you have Bite (6 points) and Claws (6 pt).<br /> You are unable to speak anything but Miu, but you can understand spoken and written words.<br /> As a quadruped, you cannot use skills that require opposable thumbs.</p>";
		break;
		case 'pahmar':
		newPage += "<p>As a Pahmar, you have Bite(20 points) and Claws (18 pt).<br /> As a large cat, you can use your claws in place of lockpicks.<br /> As a quadruped, you cannot use skills that require opposable thumbs.</p>";
		break;
		case 'senche':
		newPage += "<p>As a Senche, you have Bite (30 points) and Claws(25 pt). As a large cat, you can use your claws in place of lockpicks.<br /> As a quadruped, you cannot use skills that require opposable thumbs.</p>";
		break;
		default:
		break;
	}
	
	newPage += "<h5>Spells known</h5>";
	newPage += "<p>All Khajiit have the Eye of Fear power (Hysteria once daily).</p>";
		switch(role){
		case 'magic':
		newPage += "<p>As a mage you have learned Heal Self; Shield (10 Points); Candlelight; Courage; and your choice of Flames, Frost, or Sparks.</p>";
		break;
		default:
		newPage += "<p>All non-mages are taught Heal Self (Restore HP and SP 10 points for 1 second).</p>";
		break;
	}
		switch (morph) {
		case 'dagi':
		newPage += "<p>As a Dagi, regardless of role you know Heal Other (5 points), Shield (10 points), and Chameleon (10 percent).</p>";
		break;
		case 'alfiq':
		newPage += "<p>As an Alfiq has no hands, you have learned Telekinesis (5 pounds). Alfiq have the powers of Calming Purr and Eye of Kawaii.</p>";
		break;
		case 'pahmar':
		newPage += "<p>As a Pahmar has no hands, you have learned Telekinesis (10 pounds).</p>";
		break;
		case 'senche':
		newPage += "<p>As a Senche has no hands, you have learned Telekinesis (15 pounds).</p>";
		break;
		default:
		break;
	}
	
	newPage += "</body></html>"; //end of page!
	
  document.open();
	document.write(newPage);
	document.close();
}

//EOF